spring:
  application:
    name: grzyby

  datasource:
    url: jdbc:mysql://localhost:5001/Grzyby
    username: root
    password: toor

  jpa:
    hibernate:
      ddl-auto: create

  security:
    user:
      name: admin
      password: admin
      roles: PRACOWNIK,KIEROWNIK,MANAGER

  profiles:
    active: security
