spring:
  application:
    name: grzyby

  datasource:
    url: jdbc:mysql://localhost:3306/grzyby
    username: root
    password: toor

  jpa:
    hibernate:
      ddl-auto: create

  security:
    user:
      name: admin
      password: admin

  profiles:
    active: development